import Navbar from '@/components/common/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import AuthContext from '@/context/AuthContext';
import SWRConfigContext from '@/context/SWRConfigContext';
import { Suspense } from 'react';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='ko-KR' className={openSans.className}>
			<body className='flex'>
				<AuthContext>
					<Navbar />
					<main className='w-full'>
						<SWRConfigContext>{children}</SWRConfigContext>
					</main>
				</AuthContext>
			</body>
		</html>
	);
}
